name: terminal_snake
description: A terminal-based Snake game written in Dart
version: 2.0.4
homepage: https://github.com/ccosnean/terminal_snake.git

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.7.0

executables:
  terminal_snake: terminal_snake